library(shiny)
library(shinythemes)
library(PPBDS.data)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(gganimate)
library(plotly)
library(sf)
library(rgdal)
library(rnaturalearth)
library(rnaturalearthdata)
library(gtsummary)
library(magick)

country_data <- read_rds("data/country_data/country_data.rds")
world <- read_rds("data/country_data/world.rds")
country_data_2 <- read_rds("data/country_data/country_data_2.rds")
world_map <- read_rds("data/country_data/world_map.rds")
continent_data <- read_rds("data/continent_data/continent_data.rds")
opinion_data <- read_rds("data/opinion_data/opinion_data.rds")

