---
title: "temp_co2"
author: "Andre Ferreira"
output: html_document
---

```{r}

library(shiny)
library(shinythemes)
library(PPBDS.data)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(gganimate)
library(plotly)
library(sf)
library(rgdal)
library(rnaturalearth)
library(rnaturalearthdata)
library(gtsummary)
library(magick)

```

```{r}

co2_long_term <- read_csv("co2-concentration-long-term.csv",
                          col_types = cols(
                            Year = col_double(),
                            `CO2 concentrations (NOAA, 2018)` = col_double()
                          )) %>%
  
# This data will allow me to provide a better picture of co2 growth over the years, 
# as it has extensive data of annual co2 emissions on a global scale
  
  rename("co2_concentrations" = `CO2 concentrations (NOAA, 2018)`) %>%
  filter(Year >= 1850)

# Data cleaning

co2_long_term <- co2_long_term %>%
  ggplot(aes(x = Year,
             y = co2_concentrations)) +
  
# The graph will depict the correlation between year and global co2 emissions
  
  geom_point(aes(group = seq_along(Year))) +
  geom_line(color = "red") +
  theme_minimal() +
  transition_reveal(Year) +
  labs(title = "Global Atmospheric CO2 Concentration",
       subtitle = "Examining the Correlation Between Time & Carbon Dioxide Concentration",
       x = "Year",
       y = "CO2 Concentration (Parts per Million)")

# The GIF will consist of the points on the graph revealing themselves as time 
# continues. The other code listed above is to improve the aesthetic of the graph

anim_save("co2_concentration.gif", 
          co2_long_term)

# The anim_save function is extremely useful in converting the graph into a GIF

write_rds(co2_long_term, 
          "co2_long_term.rds")
  
# I created the rds file above to then read in within the app

```

```{r}

temp_long_term <- read_csv("temperature-anomaly.csv",
                           col_types = cols(
                             Entity = col_character(),
                             Year = col_double(),
                             `Median temperature anomaly from 1961-1990 average` = col_double(),
                             `Upper bound (95% CI)` = col_double(),
                             `Lower bound (95% CI)` = col_double()
                           )) %>%
  
# This data will allow me to provide a better picture of temperature growth over the years, 
# as it has extensive data of annual temperature medians on a global scale
  
  rename("median_temp_anomaly" = `Median temperature anomaly from 1961-1990 average`,
         "upper_bound" = `Upper bound (95% CI)`,
         "lower_bound" = `Lower bound (95% CI)`) %>%
  select(- upper_bound,
         - lower_bound) %>%
  slice(1:170)

# Data cleaning + removing columns and rows that contain irrelevant data

temp_long_term <- temp_long_term %>%
  ggplot(aes(x = Year,
             y = median_temp_anomaly)) +

# The graph will depict the correlation between year and global temperature medians

  geom_point(aes(group = seq_along(Year))) +
  geom_line(color = "blue") +
  theme_minimal() +
  transition_reveal(Year) +
  labs(title = "Median Temperature Anomaly Trend",
       subtitle = "Examining the Correlation Between Time & Global Temperature Anomalies",
       x = "Year",
       y = "Median Temperature Anomaly")

# The GIF will consist of the points on the graph revealing themselves as time 
# continues. The other code listed above is to improve the aesthetic of the graph

anim_save("temp_anomaly.gif",
          temp_long_term) 

# The anim_save function is extremely useful in converting the graph into a GIF

write_rds(temp_long_term,
          "temp_long_term.rds")

# I created the rds file above to then read in within the app

```

```{r}

co2_long_term <- read_csv("co2-concentration-long-term.csv",
                          col_types = cols(
                            Year = col_double(),
                            `CO2 concentrations (NOAA, 2018)` = col_double()
                          )) %>%
  rename("co2_concentrations" = `CO2 concentrations (NOAA, 2018)`) %>%
  filter(Year >= 1850)

temp_long_term <- read_csv("temperature-anomaly.csv",
                           col_types = cols(
                             Entity = col_character(),
                             Year = col_double(),
                             `Median temperature anomaly from 1961-1990 average` = col_double(),
                             `Upper bound (95% CI)` = col_double(),
                             `Lower bound (95% CI)` = col_double()
                           )) %>%
  rename("median_temp_anomaly" = `Median temperature anomaly from 1961-1990 average`,
         "upper_bound" = `Upper bound (95% CI)`,
         "lower_bound" = `Lower bound (95% CI)`) %>%
  select(- upper_bound,
         - lower_bound) %>%
  slice(1:170)

# This code is copied and pasted from above

correlation <- full_join(co2_long_term, 
                         temp_long_term, 
                         by = "Year") %>%
  drop_na()

# This object is created by merging the two objects defined before it and joining 
# them by using the variable entitled "Year"

write_rds(correlation, 
          "correlation.rds")

# I created the rds file above to then read in within the app

```




