---
title: "model"
author: "Andre Ferreira"
output: html_document
---

```{r}

library(shiny)
library(shinythemes)
library(PPBDS.data)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(gganimate)
library(plotly)
library(sf)
library(rgdal)
library(rnaturalearth)
library(rnaturalearthdata)
library(gtsummary)
library(magick)
library(rstanarm)
library(broom.mixed)
library(gt)

```

```{r}

brazil_ghg <- read_csv("brazil_data.csv",
                       col_types = cols(
                         .default = col_double(),
                         iso_code = col_character(),
                         country = col_character()
                       )) %>%
  
# This data includes total_ghg emissions of countries across the globe, but this 
# object will soon be filtered to only focus on Brazil's data
  
  filter(country == "Brazil",
         year >= 1900) %>%
  select(country,
         co2,
         year,
         co2_growth_prct,
         cement_co2,
         coal_co2,
         flaring_co2,
         gas_co2,
         oil_co2,
         total_ghg)

# Data cleaning
  
write_rds(brazil_ghg, 
          "brazil_ghg.rds")

# I created the rds file above to then read in within the app

```

```{r}

brazil_land_ghg <- read_csv("brazil_ghg_data.csv",
                            col_types = cols(
                              Entity = col_character(),
                              Code = col_character(),
                              Year = col_double(),
                              `Agriculture (GHG Emissions, CAIT)` = col_double(),
                              `Bunker Fuels (GHG Emissions, CAIT)` = col_double(),
                              `Industry (GHG Emissions, CAIT)` = col_double(),
                              `Land-Use Change and Forestry (GHG Emissions, CAIT)` = col_double(),
                              `Waste (GHG Emissions, CAIT)` = col_double(),
                              `Buildings (GHG Emissions, CAIT)` = col_double(),
                              `Electricity & Heat (GHG Emissions, CAIT)` = col_double(),
                              `Fugitive from energy production (GHG Emissions, CAIT)` = col_double(),
                              `Manufacturing/Construction energy (GHG Emissions, CAIT)` = col_double(),
                              `Other Fuel Combustion (GHG Emissions, CAIT)` = col_double(),
                              `Transport (GHG Emissions, CAIT)` = col_double()
                            )) %>%
  
# This data tells me how much ghg emissions are produced annually by land-use, while
# the other data set only includes carbon emissions. I will need to merge the two to 
# complete my model
  
  select(Entity,
         Year,
         `Land-Use Change and Forestry (GHG Emissions, CAIT)`) %>%
  filter(Entity == "Brazil",
         Year >= 1900) %>%
  rename("country" = Entity,
         "year" = Year,
         "land_use" = `Land-Use Change and Forestry (GHG Emissions, CAIT)`)

# Data cleaning

write_rds(brazil_land_ghg, 
          "brazil_land_ghg.rds")
  
# I created the rds file above to then read in within the app

```

```{r}

brazil <- full_join(brazil_ghg, 
                    brazil_land_ghg, 
                    by = "year") %>%
  drop_na()

# This object is created by merging the two objects defined before it and joining 
# them by using the variable entitled "year"

write_rds(brazil, 
          "brazil.rds")

# I created the rds file above to then read in within the app

```

```{r}

brazil_fit <- stan_glm(data = brazil_ghg,
                       family = gaussian(),
                       formula = total_ghg ~ gas_co2 + cement_co2 + flaring_co2 + oil_co2 + coal_co2,
                       refresh = 0)

# The object defined above uses the stan_glm function to create a regression that models
# total_ghg using five variables, specifically the five main producers of carbon emissions

write_rds(brazil_fit, 
          "brazil_fit.rds")

# I created the rds file above to then read in within the app

```

```{r}

brazil_land_fit <- stan_glm(data = brazil,
                       family = gaussian(),
                       formula = total_ghg ~ co2 + land_use,
                       refresh = 0)

# The object defined above uses the stan_glm function to create a regression that models
# total_ghg using two variables, specifically the value of annual carbon emissions and 
# annual land_use 

write_rds(brazil_land_fit, 
          "brazil_land_fit.rds")

# I created the rds file above to then read in within the app

```

```{r}

brazil_table <- tbl_regression(brazil_fit, 
                               exponentiate = TRUE)

# This object creates a table that depicts my regression created in the object
# brazil_fit. It displays the 95% confidence interval for each variable as well
# as the beta value

brazil_table <- brazil_table %>%
  modify_table_header(column = estimate,
                      label = "**Beta**") %>%
  as_gt() %>%
  tab_header(title = "Regression of Greenhouse Gas Emissions in Brazil")

# The code above improves the aesthetic of the regression table

write_rds(brazil_table, 
          "brazil_table.rds")

# I created the rds file above to then read in within the app

```

```{r}

brazil_land_table <- tbl_regression(brazil_land_fit, 
                               exponentiate = TRUE)

# This object creates a table that depicts my regression created in the object
# brazil_land_fit. It displays the 95% confidence interval for each variable as well
# as the beta value

brazil_land_table <- brazil_land_table %>%
  modify_table_header(column = estimate,
                      label = "**Beta**") %>%
  as_gt() %>%
  tab_header(title = "Regression of GHG in Brazil Factoring in Land Use")

# The code above improves the aesthetic of the regression table

write_rds(brazil_land_table, 
          "brazil_land_table.rds")

# I created the rds file above to then read in within the app

```







