---
title: "continent_data"
author: "Andre Ferreira"
output: html_document
---

```{r}

library(shiny)
library(shinythemes)
library(PPBDS.data)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(gganimate)
library(plotly)
library(sf)
library(rgdal)
library(rnaturalearth)
library(rnaturalearthdata)
library(gtsummary)
library(magick)

```

```{r}

continent_data <- read_csv("continent_info.csv",
                           col_types = cols(
                             .default = col_double(),
                             iso_code = col_character(),
                             country = col_character()
                           )) %>%
  
# The code above will read in the csv file I want to work with. Within the csv file,
# contains loads of information regarding six continents, including
# carbon emissions, gdp, population, etc. Antarctica is not included due to lack
# of data. 
  
  select(co2,
         co2_growth_prct,
         country,
         year) %>%
  filter(country %in% c("Africa",
                        "Asia",
                        "Australia",
                        "Europe",
                        "North America",
                        "South America"),
         year >= 1850) %>%
  
# This data filters the csv file, so that it only includes rows with data about 
# the continents listed above
  
  drop_na(co2_growth_prct)

write_rds(continent_data, "continent_data.rds")

# I created the rds file above to then read in within the app

```


